# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('activecode', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
