# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('activecode', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=None)),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('A', 'Accepted'), ('C', 'Closed')], default='W', max_length=1)),
                ('headline', models.CharField(default='New Task', max_length=16)),
                ('detail', models.CharField(default='New Task', max_length=128)),
                ('reward', models.CharField(default='1 RMB', max_length=16)),
                ('create_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_account', to='Errand.Account')),
                ('execute_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute_account', to='Errand.Account')),
                ('response_accounts', models.ManyToManyField(to='Errand.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None)),
                ('place', models.CharField(default='classroom', max_length=16)),
                ('action', models.CharField(default='do something', max_length=50)),
                ('task_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_actions', to='Errand.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='John', max_length=16)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone_number', models.CharField(default='13000000000', max_length=11)),
                ('birthday', models.DateField(default=datetime.date(2016, 5, 15))),
                ('signature', models.CharField(blank=True, default='', max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Errand.Userinfo'),
        ),
    ]
