# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='John', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='Userinfo',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Errand.Userinfo'),
            preserve_default=False,
        ),
    ]
