# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='response_accounts',
            field=models.ManyToManyField(related_name='response_account', to='Errand.Account'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.date(2016, 5, 19)),
        ),
    ]
