# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0002_auto_20160502_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Userinfo',
            new_name='userinfo',
        ),
    ]
