# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0002_auto_20160519_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default='1900-1-1'),
        ),
    ]
