# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0003_auto_20160519_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execute_accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute_tasks', to='Errand.Account'),
        ),
        migrations.AlterField(
            model_name='task',
            name='response_accounts',
            field=models.ManyToManyField(related_name='response_tasks', to='Errand.Account'),
        ),
    ]
