# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0003_auto_20160503_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.date(2016, 5, 5)),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default='13000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
