# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0004_auto_20160519_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='execute_accounts',
            new_name='execute_account',
        ),
    ]
