# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0005_auto_20160521_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(default='No Comment', max_length=128),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
