# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Errand', '0006_auto_20160521_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Errand.Userinfo'),
        ),
    ]
